### ISSUE TITLE
Fix the SSLFilter crash

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/CoreLibs#228]
New packet arrives in SSL filter while asynchronous operation is still running. 
We should not pass new data in protocol filters until asynchronous operations are completed.

```
#3  0x00007ffff6f70c82 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00000000008600b3 in ProtocolFilters::SSLFilter::processNewConnectionData (this=0x7fffe4294550, dd=ProtocolFilters::DD_INPUT, 
    pd=ProtocolFilters::PD_SEND, p_data=0x7fffe44a7a20 "", length=249)
    at /home/user/work/core/proxy/nfsdk-src/ProtocolFilters/SSLFilter.cpp:1287
#5  0x00000000008637ca in ProtocolFilters::SSLFilter::tcp_packet (this=0x7fffe4294550, dd=ProtocolFilters::DD_INPUT, 
    pd=ProtocolFilters::PD_SEND, buf=0x7fffe44a7a20 "", len=249)
    at /home/user/work/core/proxy/nfsdk-src/ProtocolFilters/SSLFilter.cpp:2547
#6  0x0000000000856324 in ProtocolFilters::ProxySession::tcp_packet (this=0x7fffe4294190, pSourceFilter=0x7fffe42f6060, 
    dd=ProtocolFilters::DD_INPUT, pd=ProtocolFilters::PD_SEND, buf=0x7fffe44a7a20 "", len=249, continueFromSpecFilter=false)
    at /home/user/work/core/proxy/nfsdk-src/ProtocolFilters/ProxySession.cpp:337
#7  0x00000000008633ba in ProtocolFilters::SSLFilter::processOutgoingDataExchange (this=0x7fffe42f6060, 
    pdReal=ProtocolFilters::PD_SEND, pdReverse=ProtocolFilters::PD_RECEIVE, p_data=0x7ffff4f3b2d0 "\027\003\003\001\021", length=278)
    at /home/user/work/core/proxy/nfsdk-src/ProtocolFilters/SSLFilter.cpp:2436
#8  0x00000000008636d9 in ProtocolFilters::SSLFilter::processDataExchange (this=0x7fffe42f6060, pd=ProtocolFilters::PD_SEND, 
    p_data=0x7ffff4f3b2d0 "\027\003\003\001\021", length=278) at /home/user/work/core/proxy/nfsdk-src/ProtocolFilters/SSLFilter.cpp:2518
#9  0x000000000086387e in ProtocolFilters::SSLFilter::tcp_packet (this=0x7fffe42f6060, dd=ProtocolFilters::DD_INPUT, 
    pd=ProtocolFilters::PD_SEND, buf=0x7ffff4f3b2d0 "\027\003\003\001\021", len=278)
    at /home/user/work/core/proxy/nfsdk-src/ProtocolFilters/SSLFilter.cpp:2571
#10 0x0000000000856324 in ProtocolFilters::ProxySession::tcp_packet (this=0x7fffe4294190, pSourceFilter=0x0, 
    dd=ProtocolFilters::DD_INPUT, pd=ProtocolFilters::PD_SEND, buf=0x7ffff4f3b2d0 "\027\003\003\001\021", len=278, 
    continueFromSpecFilter=false) at /home/user/work/core/proxy/nfsdk-src/ProtocolFilters/ProxySession.cpp:337
#11 0x0000000000851a0f in ProtocolFilters::Proxy::tcpSend (this=0xfbd400 <g_proxy>, id=1000140, 
    buf=0x7ffff4f3b2d0 "\027\003\003\001\021", len=278) at /home/user/work/core/proxy/nfsdk-src/ProtocolFilters/Proxy.cpp:117
#12 0x000000000061cb5e in AGPFAccessor::indicateDataFromClient(unsigned long long, char const*, int) ()
    at /usr/include/c++/5/bits/basic_string.h:5010
#13 0x000000000061f6bf in AGProxySession::onRead(AGVSocket*, char const*, unsigned long) ()
    at /usr/include/c++/5/bits/basic_string.h:5010
#14 0x00000000006a66eb in AGFDVSocket::onRead(bufferevent*, void*) () at /usr/include/c++/5/bits/basic_string.h:5010
```

**Comment by sxgunchenko** [comment]
Merged, core/pull-requests/270
