### ISSUE TITLE
Error while searching for a connection ID

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#235]
It seems that it happened in `getTcpConnectionIdByAddrPort`.

Or, what's more likely, `getTcpConnectionIdByAddrPort` has returned `null`.

```
 java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
 	at com.adguard.android.filtering.api.LocalVpnService.findTcpConnectionId(LocalVpnService.java:177) ~[na:0.0]
 	at com.adguard.android.filtering.filter.ConnectionsManager.findProxyConnectionInfo(ConnectionsManager.java:128) ~[na:0.0]
 	at com.adguard.android.filtering.filter.FilteringProxyServer.resolveConnectionInfo(FilteringProxyServer.java:100) ~[na:0.0]
 	at com.adguard.filter.proxy.TcpListener.createTcpConnectionContext(TcpListener.java:244) ~[na:0.0]
 	at com.adguard.filter.proxy.TcpListener.acceptConnection(TcpListener.java:332) ~[na:0.0]
 	at com.adguard.filter.proxy.TcpListener.access$100(TcpListener.java:30) ~[na:0.0]
 	at com.adguard.filter.proxy.TcpListener$2.run(TcpListener.java:311) ~[na:0.0]
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) ~[na:0.0]
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) ~[na:0.0]
 	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
```

**Comment by sfionov** [comment]
getTcpConnectionIdBySocketAddress may return null by design (if no such connection exists in TCP stack)

**Comment by ameshkov** [comment]
Smth is not okay with the method contract then, otherwise this exception
would not be possible

**Comment by ameshkov** [comment]
The mistake is on the app side after all
