### ISSUE TITLE
Failed to start the proxy server due to an SSL filter initialization error

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#349]
```
11:50:11.817 [protection-pool-1-thread-2] DEBUG Native.PF - (SSSLDataProvider) LoadMap error offset: 11
11:50:11.818 [protection-pool-1-thread-2] ERROR com.adguard.android.filtering.api.h - An error occurred while starting protection. Making sure that the proxy servers are stopped
11:50:11.818 [protection-pool-1-thread-2] INFO  com.adguard.android.filtering.a.b - Proxy server is already closed
11:50:11.822 [protection-pool-1-thread-2] ERROR com.adguard.android.service.y - Cannot start protection

java.io.IOException: failed to initialize proxy server (Failed to initialize protocol filters (Try again))
	at com.adguard.corelibs.proxy.ProxyServerImpl.start(Native Method) ~[na:0.0]
	at com.adguard.corelibs.proxy.ProxyServerImpl.start(Unknown Source:2) ~[na:0.0]
	at com.adguard.android.filtering.a.b.a(Unknown Source:39) ~[na:0.0]
	at com.adguard.android.filtering.api.i.a(Unknown Source:158) ~[na:0.0]
	at com.adguard.android.service.ah.a(Unknown Source:158) ~[na:0.0]
	at com.adguard.android.service.y.run(Unknown Source:15) ~[na:0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:0.0]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
```

[adguard_logs_2.12.60_1806_1153.zip](https://github.com/AdguardTeam/CoreLibs/files/2110607/adguard_logs_2.12.60_1806_1153.zip)

**Comment by sfionov** [comment]
SSL storage should be invalidated, if it is damaged (e.g. due to filesystem problems after turning off the phone).

**Comment by szolin** [comment]
core/pull-requests/414

**Comment by szolin** [comment]
core/pull-requests/435
