### ISSUE TITLE
Deadlock in multi-threaded mode

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#99]
```
Thread 5 (Thread 0x7fbb49aa6700 (LWP 10032)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007fbb4b8a4f8a in __GI___pthread_mutex_lock (mutex=0x7fbb440db468) at ../nptl/pthread_mutex_lock.c:115
#2  0x000055d809486eb3 in __gthread_mutex_lock (__mutex=0x7fbb440db468) at /usr/include/x86_64-linux-gnu/c++/6/bits/gthr-default.h:748
#3  0x000055d809486f03 in __gthread_recursive_mutex_lock (__mutex=0x7fbb440db468) at /usr/include/x86_64-linux-gnu/c++/6/bits/gthr-default.h:810
#4  0x000055d809488e6c in std::recursive_mutex::lock (this=0x7fbb440db468) at /usr/include/c++/6/mutex:105
#5  0x000055d80948a7e9 in std::unique_lock<std::recursive_mutex>::lock (this=0x7fbb49aa5a10) at /usr/include/c++/6/bits/std_mutex.h:267
#6  0x000055d8094897c2 in std::unique_lock<std::recursive_mutex>::unique_lock (this=0x7fbb49aa5a10, __m=...) at /usr/include/c++/6/bits/std_mutex.h:197
#7  0x000055d8094b7e66 in AGProxySession::onWriteFlush (this=0x7fbb440db370, socket=0x7fbb440dae90) at /adguard-builddir/proxy/main/src/AGProxySession.cpp:517
#8  0x000055d809515fef in AGFDVSocket::onWriteFlush (bev=0x7fbb440dafd0, ctx=0x7fbb440dae90) at /adguard-builddir/proxy/vsocket/src/AGFDVSocket.cpp:169
#9  0x000055d8095ac49c in bufferevent_run_writecb_ (bufev=0x7fbb440dafd0, options=0) at /adguard-builddir/third-party/libevent/libevent-2.1.8-stable/bufferevent.c:248
#10 0x000055d8095b14d1 in bufferevent_trigger_nolock_ (bufev=0x7fbb440dafd0, iotype=4, options=0) at /adguard-builddir/third-party/libevent/libevent-2.1.8-stable/bufferevent-internal.h:397
#11 0x000055d8095b1b08 in bufferevent_writecb (fd=37, event=4, arg=0x7fbb440dafd0) at /adguard-builddir/third-party/libevent/libevent-2.1.8-stable/bufferevent_sock.c:323
#12 0x000055d8095b90e1 in event_persist_closure (base=0x55d80c1346f0, ev=0x7fbb440db060) at /adguard-builddir/third-party/libevent/libevent-2.1.8-stable/event.c:1580
#13 0x000055d8095b93e5 in event_process_active_single_queue (base=0x55d80c1346f0, activeq=0x55d80c134b40, max_to_process=2147483647, endtime=0x0) at /adguard-builddir/third-party/libevent/libevent-2.1.8-stable/event.c:1639
#14 0x000055d8095b9a22 in event_process_active (base=0x55d80c1346f0) at /adguard-builddir/third-party/libevent/libevent-2.1.8-stable/event.c:1738
#15 0x000055d8095ba1a5 in event_base_loop (base=0x55d80c1346f0, flags=4) at /adguard-builddir/third-party/libevent/libevent-2.1.8-stable/event.c:1961
#16 0x000055d809513ff4 in AGEventLoop::run (this=0x55d80bebb470) at /adguard-builddir/proxy/vsocket/src/AGEventLoop.cpp:64
#17 0x000055d80958475e in AGThread::run_thread (attr=0x55d80bebb470) at /adguard-builddir/commons/src/AGThread.cpp:11
#18 0x000055d809585732 in std::_Bind_simple<void (*(AGThread*))(void*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x55d80c134d28) at /usr/include/c++/6/functional:1391
#19 0x000055d809585670 in std::_Bind_simple<void (*(AGThread*))(void*)>::operator()() (this=0x55d80c134d28) at /usr/include/c++/6/functional:1380
#20 0x000055d809585640 in std::thread::_State_impl<std::_Bind_simple<void (*(AGThread*))(void*)> >::_M_run() (this=0x55d80c134d20) at /usr/include/c++/6/thread:197
#21 0x00007fbb4b5ce83f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#22 0x00007fbb4b8a26da in start_thread (arg=0x7fbb49aa6700) at pthread_create.c:456
#23 0x00007fbb4b03d17f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 3 (Thread 0x7fbb4a2a7700 (LWP 10030)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007fbb4b8a4f8a in __GI___pthread_mutex_lock (mutex=0x7fbb440db310) at ../nptl/pthread_mutex_lock.c:115
#2  0x000055d8095c41bb in evthread_posix_lock (mode=0, lock_=0x7fbb440db310) at /adguard-builddir/third-party/libevent/libevent-2.1.8-stable/evthread_pthread.c:75
#3  0x000055d8095ad4c9 in bufferevent_incref_and_lock_ (bufev=0x7fbb440dafd0) at /adguard-builddir/third-party/libevent/libevent-2.1.8-stable/bufferevent.c:661
#4  0x000055d8095acbed in bufferevent_enable (bufev=0x7fbb440dafd0, event=2) at /adguard-builddir/third-party/libevent/libevent-2.1.8-stable/bufferevent.c:467
#5  0x000055d8095159dd in AGFDVSocket::wantRead (this=0x7fbb440dae90, flag=true) at /adguard-builddir/proxy/vsocket/src/AGFDVSocket.cpp:92
---Type <return> to continue, or q <return> to quit---
#6  0x000055d8094b4b9c in AGProxySession::start (this=0x7fbb440db370) at /adguard-builddir/proxy/main/src/AGProxySession.cpp:86
#7  0x000055d809487aa6 in AGProxyServer::createSession (this=0x55d80a2b4330, clientSocket=0x7fbb440dae90, remoteSocket=0x0, socketFactory=std::shared_ptr (count 3, weak 1) 0x7fbb440dae10)
    at /adguard-builddir/proxy/main/src/AGProxyServer.cpp:98
#8  0x000055d80946f67d in AGStandaloneProxyServer::onNewConnection (this=0x55d80a2b4330, fd=37, address=...) at /adguard-builddir/proxy/main/test/AGStandaloneProxyServer.cpp:109
#9  0x000055d80946efa8 in AGStandaloneProxyServer::onAcceptedEvent (listener=0x55d80c1356b0, fd=37, sa=0x7fbb4a2a6a80, salen=28, data=0x55d80a2b4330) at /adguard-builddir/proxy/main/test/AGStandaloneProxyServer.cpp:66
#10 0x000055d8095c9de3 in listener_read_cb (fd=23, what=2, p=0x55d80c1356b0) at /adguard-builddir/third-party/libevent/libevent-2.1.8-stable/listener.c:418
#11 0x000055d8095b90e1 in event_persist_closure (base=0x55d80beba4c0, ev=0x55d80c1356e8) at /adguard-builddir/third-party/libevent/libevent-2.1.8-stable/event.c:1580
#12 0x000055d8095b93e5 in event_process_active_single_queue (base=0x55d80beba4c0, activeq=0x55d80beba8f0, max_to_process=2147483647, endtime=0x0) at /adguard-builddir/third-party/libevent/libevent-2.1.8-stable/event.c:1639
#13 0x000055d8095b9a22 in event_process_active (base=0x55d80beba4c0) at /adguard-builddir/third-party/libevent/libevent-2.1.8-stable/event.c:1738
#14 0x000055d8095ba1a5 in event_base_loop (base=0x55d80beba4c0, flags=4) at /adguard-builddir/third-party/libevent/libevent-2.1.8-stable/event.c:1961
#15 0x000055d809513ff4 in AGEventLoop::run (this=0x55d80a68d700) at /adguard-builddir/proxy/vsocket/src/AGEventLoop.cpp:64
#16 0x000055d80958475e in AGThread::run_thread (attr=0x55d80a68d700) at /adguard-builddir/commons/src/AGThread.cpp:11
#17 0x000055d809585732 in std::_Bind_simple<void (*(AGThread*))(void*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x55d80bebaad8) at /usr/include/c++/6/functional:1391
#18 0x000055d809585670 in std::_Bind_simple<void (*(AGThread*))(void*)>::operator()() (this=0x55d80bebaad8) at /usr/include/c++/6/functional:1380
#19 0x000055d809585640 in std::thread::_State_impl<std::_Bind_simple<void (*(AGThread*))(void*)> >::_M_run() (this=0x55d80bebaad0) at /usr/include/c++/6/thread:197
#20 0x00007fbb4b5ce83f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#21 0x00007fbb4b8a26da in start_thread (arg=0x7fbb4a2a7700) at pthread_create.c:456
#22 0x00007fbb4b03d17f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```

**Comment by sfionov** [comment]
Merged, core/pull-requests/49
